#sleep_for_a_minute <- function() { Sys.sleep(60) }
start_time <- Sys.time()
#sleep_for_a_minute
#data preparation
#load library data
library(xtail)
#read in datasets
mrna <- read.table("WT_EMTAB6196.txt",header = TRUE, row.names = 1)
rpf <- read.table("RPF_EMTAB6196.txt",header = TRUE, row.names = 1)
#set conditions
condition <- c("GpB","GpB","GpA","GpA","GpA","GpA","GpA","GpA")
#create a variable for xtail results to go to 
test_6196_results <- xtail(mrna,rpf,condition)
#put results into table format
test.tab <- resultsTable(test_6196_results)
#export plain text file
write.table(test.tab,"test_6196_results.txt",quote=F,sep = "\t")
#export xtail results to tab delim file
write.xtail(test_6196_results,"test_6196_results.txt",quote=F,sep="\t")

  #xdata <- RPF_EMTAB6196
#Xtaildata <- RPF_EMTAB6196
#data(xdata)
#data2(RPF_EMTAB6196)
#data(WT_EMTAB6196)
#data(RPF_EMTAB6196)

#view first 5 lines of mrna and RPF elements
#mrna <- xtaildata$mrna
#rpf <- xtaildata$rpf
#head(mrna,5)
#head(rpf,5)
#mrna <- xtaildata$mrna
#rpf <- xtaildata$rpf
#head(mrna,5)
#head(rpf,5)
#assign condition labels to columns of both datasets
#run main function, default= second condition of treat would be compared to first which is control
# minimum average expression genes of mRNA and rpf counts larger than ione are used.- altered by minMeanCount
#bins argument is used to calculate probability densities of log2FC and log2R- determines accuracy of pvalue
#bins also sets running time
#test.results <- xtail(mrna,rpf,condition,bins = 1000)


#summarise basic results
#summary(test.results)# results slightly different, log2FC and log2R are smaller and larger
#extend results table using resultsTable and examine first 5 lines of table
#test.tab <- resultsTable(test.results)
#head(test.tab,5)
#first pipeline results use v1 suffix and are generated by comparing mRNA and RPF log2 fold changes
#log2FC_TE_v1 is changes of TE, pvalue represents statistical significance
#second pipeline uses v2 suffix and are derived from log2 ratios of 2 conditions v2 and pvalues. 
#more conserved results(larger p-values) selected as final assessment of translation= _final
#p-value.adjust estaimted false discovery rate linked to p-value_final





#visualisation
#plotFC's- shows result of differential expression at 2 levels- each gene is a dot whose position is determiend by log2 fold change(log2FC)
#plotFCs(test.results)
#genese where difference of log2FC for mRNA and RPF did not exceed more than the cutoff. they are excluded. default cutoff is 1

#plotRs
#positions determined by RPF to mRNA ratio in 2 conditions
#plotRs(test.results)
#genes where difference of log2R in 2 conditions did not exceed cutoff are excluded 

#volcanoPlot
#evaluate fold changes cutodd and p-values thresholds
#volcanoPlot(test.results)


end_time <- Sys.time()
end_time - start_time

