start_time <- Sys.time()

#install.packages(c("cluster.datasets"), dependencies = TRUE)

#data preparation
#load library data
library(xtail)
#read in datsets
mrna <- read.table("MRNA_EXCEL.csv",header = TRUE,row.names = 1)
rpf <- read.table("RPF_EXCEL.csv",header = TRUE,row.names = 1)
#set conditions
condition <- c("Control","Control","Treated","Treated")
#create a variable for xtail results to go to 
xtail_3805_results <- xtail(mrna,rpf,condition)

#summarise basic results
summary(xtail_3805_results)# results slightly different, log2FC and log2R are smaller and larger
#extend results table using resultsTable and examine first 5 lines of table
xtail.tab <- resultsTable(xtail_3805_results)

#first pipeline results use v1 suffix and are generated by comparing mRNA and RPF log2 fold changes
#log2FC_TE_v1 is changes of TE, pvalue represents statistical significance
#second pipeline uses v2 suffix and are derived from log2 ratios of 2 conditions v2 and pvalues. 
#more conserved results(larger p-values) selected as final assessment of translation= _final
#p-value.adjust estaimted false discovery rate linked to p-value_final

#export plain text file
write.table(xtail.tab,"xtail_3805_results.txt",quote=F,sep = "\t")
#export xtail results to tab delim file
write.xtail(xtail_3805_results,"xtail_3805_results.txt",quote=F,sep="\t")

end_time <- Sys.time()
end_time - start_time


